=== fazarei/VlineDriverVersion2/com/netdimen/core/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 1999-2006 NetDimensions Ltd.

  All rights reserved.

  This document is the confidential and proprietary information of NetDimensions
  Ltd. ("Confidential Information").  You shall not disclose such Confidential
  Information and shall use it only in accordance with the terms of the license
  agreement you entered into with NetDimensions.
-->
<!-- This is the XML Schema for the EKP deployment descriptor. -->
<xs:schema xmlns="http://www.netdimensions.com/xml/ns/components"
           targetNamespace="http://www.netdimensions.com/xml/ns/components"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <!--
    The access-level element contains the type of access required to access the
    transaction.

    The access-level element must be one of the following:
                    <access-level>ReadAccess</access-level>
                    <access-level>WriteAccess</access-level>

    Used in: transaction
  -->
  <xs:element name="access-level" type="xs:string"/>
  <!--
    The cacheable element indicates that a browser may store a cached copy of any
    page generated by a transaction.

    Used in: transaction
  -->
  <xs:element name="cacheable">
    <xs:complexType/>
  </xs:element>
  <!--
    The class element contains the fully-qualified name of the transaction's class.

    Used in: transaction

    Example:
                    <class>com.netdimen.tx.test.StartTest</class>
  -->
  <xs:element name="class" type="xs:string" />
  <!-- The components element is the root element of the deployment descriptor. -->
  <xs:element name="components">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="charts"/>
        <xs:element ref="reports"/>
        <xs:element ref="transactions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--
    The container-transaction specifies whether the container will automatically
    manage transaction demarcation on behalf of the component.

    Used in: transaction
  -->
  <xs:element name="container-transaction" type="xs:boolean"/>
  <!--
    The nonblocking-transaction specifies whether the TX is allowed to
    perform a dirty read.

    Used in: transaction
  -->
  <xs:element name="nonblocking-transaction" type="xs:boolean"/>
  <!--
    The feature element specifies the EKP feature to which the transaction belongs.

    Used in: transaction

    Example:
                    <feature>Tests</feature>
  -->
  <xs:element name="feature" type="xs:string"/>
  
  
  
  <xs:element name="indicator">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="indicator-code"/>
        <xs:element ref="indicator-class"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="indicator-code" type="xs:integer"/>
  <xs:element name="indicator-class" type="xs:string"/>

  <xs:element name="charts">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="indicator"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
  
  <!--
    The report element declares a report. The declaration consists of a report name
    and the name of the implementation class.

    Used in: components
  -->
  <xs:element name="report">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="report-name"/>
        <xs:element ref="report-class"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--
    The report-class elements contains the fully-qualified name of the report's
    class.

    Used in: report
  -->
  <xs:element name="report-class" type="xs:string"/>
  <!--
    The report-name element contains a unique name used to identifiy the report.

    Used in: report
  -->
  <xs:element name="report-name" type="xs:string"/>
  <!--
    The reports element contains a list of reports.

    Used in: components
  -->
  <xs:element name="reports">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="report"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    <!--
      The requires-authentication element specifies whether the transaction requires
      authentication.

      The requires-authentication element must be one of the following:
                      <requires-authentication>true</requires-authentication>
                      <requires-authentication>false</requires-authentication>

      Used in: transaction
    -->
    <xs:element name="requires-authentication" type="xs:string"/>
    <!--
       The requires-e-signature element specifies whether the transaction requires
       e-signature.

       The requires-e-signature element must be one of the following:
                       <requires-e-signature>true</requires-e-signature>
                       <requires-e-signature>false</requires-e-signature>

       Used in: transaction
     -->
    <xs:element name="requires-e-signature" type="xs:boolean"/>

    <!--
      The requires-secure element indicates that the transaction must be accessed
      using a secure protocol such as HTTPS.

      Used in: transaction
    -->
    <xs:element name="requires-secure">
    <xs:complexType/>
  </xs:element>
  <!--
    The transaction element declares a transaction. The declaration consists of: a
    transaction code; a feature code; an access level code; the name of the
    implementation class; a flag indicating whether authentication is required to
    access the transaction; and the name of the resource bundle used by the
    transaction.

    Used in: transactions
  -->
  <xs:element name="transaction">
    <xs:complexType>
		<xs:sequence>
			<xs:element ref="tx-code"/>
			<xs:element minOccurs="0" ref="tx-type"/>
			<xs:element ref="feature"/>
			<xs:element ref="access-level"/>
			<xs:element ref="class"/>
			<xs:element ref="requires-authentication"/>
			<xs:element ref="requires-e-signature" minOccurs="0" maxOccurs="1"/>
			<xs:element minOccurs="0" ref="cacheable"/>
			<xs:element minOccurs="0" ref="requires-secure"/>
			<xs:element minOccurs="0" ref="container-transaction"/>
			<xs:element minOccurs="0" ref="nonblocking-transaction"/>
			<xs:element minOccurs="0" name="unsafe" type="xs:boolean"/>
			<xs:element minOccurs="0" name="parallel-tx" type="xs:boolean"/>
		</xs:sequence>
		<xs:attribute name="gadget" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <!--
    The transactions element contains a list of transactions.

    Used in: components
  -->
  <xs:element name="transactions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="transaction"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--
    The tx-code element contains a unique code used to access the transaction.

    Used in: transaction

    Example:
                    <tx-code>STARTTEST</tx-code>
  -->
  <xs:element name="tx-code" type="xs:string"/>
  <!--
    The tx-type element identifies how a specific TX is used, thus facilitating
    creation if internal usage selection lists.  Basic values are:

    HOMEPAGE, TOPMENU, LEFTMENU, BOTTOMMENU, CATALOGFORMAT, DEFAULT

    Used in: transaction

    Example:
                    <tx-type>HOMEPAGE</tx-type>
  -->
  <xs:element name="tx-type" type="xs:string"/>
</xs:schema>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/specsavers/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision: 1.170.2.18 $
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">
<reports>
    <report>
      <report-name>ReportR250SS</report-name>
      <report-class>com.netdimen.custom.specsavers.newreports.configurators.ConfiguratorR250SS</report-class>
    </report>
</reports>
<transaction>
	<tx-code>LISTTRAN</tx-code>
	<feature>MyTranscript</feature>
	<access-level>ReadAccess</access-level>
	<class>com.netdimen.custom.specsavers.tx.transcript.ListTran</class>
	<requires-authentication>true</requires-authentication>
</transaction>
<transaction>
	<tx-code>TABLISTTRAN</tx-code>
	<feature>MyTranscript</feature>
	<access-level>ReadAccess</access-level>
	<class>com.netdimen.custom.specsavers.tx.transcript.TabListTran</class>
	<requires-authentication>true</requires-authentication>
	<nonblocking-transaction>true</nonblocking-transaction>
</transaction>

</components>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/bbc/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision$
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">
    <reports>
        <report>
              <report-name>ReportR200BBC</report-name>
              <report-class>com.netdimen.custom.bbc.newreports.configurators.ConfiguratorR200BBC</report-class>
        </report>
    </reports>
	<transactions>
		<transaction>
			<tx-code>CATALOGSELECTOR</tx-code>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.tx.util.CatalogSelector</class>
			<requires-authentication>false</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>MOBILEFREELANCERS</tx-code>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.bbc.tx.MobileFreelancers</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>BBCFOOTER</tx-code>
			<tx-type>MENU</tx-type>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.bbc.tx.screen.BbcFooter</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
	</transactions>
</components>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/cathay/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision: 1.1 $
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">

	<transactions>
		<transaction>
			<tx-code>TextSide</tx-code>
			<tx-type>MENU</tx-type>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.cathay.tx.screen.TextSide</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
	</transactions>
</components>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/livss/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision: 1.0.0.0 $
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">
	<transactions>
		<transaction>
			<tx-code>LIVSSHOMETX</tx-code>
			<feature>MyRecordsMenu</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.livss.tx.LivssHomeTx</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LIVSSREQUESTTX</tx-code>
			<feature>MyRecordsMenu</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.livss.tx.LivssRequestTx</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LIVSSSUBMITTX</tx-code>
			<feature>MyRecordsMenu</feature>
			<access-level>READAccess</access-level>
			<class>com.netdimen.custom.livss.tx.LivssSubmitTx</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LIVSSRESPONSETX</tx-code>
			<feature>MyRecordsMenu</feature>
			<access-level>READAccess</access-level>
			<class>com.netdimen.custom.livss.tx.ResponseListTx</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LIVSSSUBMITRESPONSETX</tx-code>
			<feature>MyRecordsMenu</feature>
			<access-level>READAccess</access-level>
			<class>com.netdimen.custom.livss.tx.ResponseSubmitTx</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LIVSSREVIEWTX</tx-code>
			<feature>MyRecordsMenu</feature>
			<access-level>READAccess</access-level>
			<class>com.netdimen.custom.livss.tx.LivssReviewTx</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LIVSSMENULEFT</tx-code>
			<tx-type>MENU</tx-type>
			<feature>System</feature>
			<access-level>READAccess</access-level>
			<class>com.netdimen.custom.livss.LivssMenuLeft</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
	</transactions>
</components>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/threem/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision: 1.0.0.0 $
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">

	<transactions>
		<transaction>
			<tx-code>TMHOMETX</tx-code>
			<tx-type>HOMEPAGE</tx-type>
			<feature>MyHome</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.threem.tx.ThreeMHomeTx</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
	</transactions>
</components>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/mott/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision$
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">

	<reports>
		<report>
			<report-name>ReportR109M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR109M</report-class>
		</report>
		<report>
			<report-name>ReportR140M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR140M</report-class>
		</report>
		<report>
			<report-name>ReportR141M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR141M</report-class>
		</report>
		<report>
			<report-name>ReportR142M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR142M</report-class>
		</report>
		<report>
			<report-name>ReportR240M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR240M</report-class>
		</report>
		<report>
			<report-name>ReportR241M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR241M</report-class>
		</report>
		<report>
			<report-name>ReportR243M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR243M</report-class>
	    </report>
		<report>
			<report-name>ReportR244M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR244M</report-class>
		</report>
		<report>
			<report-name>ReportR245M</report-name>
			<report-class>com.netdimen.custom.mott.newreports.configurator.ConfiguratorR245M</report-class>
		</report>
	</reports>
	<transactions>
		<transaction>
			<tx-code>R245M</tx-code>
			<feature>BSReports</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.mott.newreports.generator.ReportR245M</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LAUNCHWORKINGMANAGER</tx-code>
			<tx-type>HOMEPAGE</tx-type>
			<feature>System</feature>
			<access-level>WriteAccess</access-level>
			<class>com.netdimen.custom.mott.tx.LaunchWorkingManager</class>
			<requires-authentication>true</requires-authentication>
			<container-transaction>true</container-transaction>
		</transaction>
		<transaction>
			<tx-code>REDIRECTWITHUSERID</tx-code>
			<tx-type>HOMEPAGE</tx-type>
			<feature>System</feature>
			<access-level>WriteAccess</access-level>
			<class>com.netdimen.custom.mott.tx.RedirectWithUserid</class>
			<requires-authentication>true</requires-authentication>
			<container-transaction>true</container-transaction>
		</transaction>
	</transactions>
</components>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/progress/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision$
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">

	<reports>
		<report>
			<report-name>ReportR112P</report-name>
			<report-class>com.netdimen.custom.progress.newreports.configurators.ConfiguratorR112P</report-class>
		</report>
		<report>
			<report-name>ReportR116P</report-name>
			<report-class>com.netdimen.custom.progress.newreports.configurators.ConfiguratorR116P</report-class>
		</report>
	</reports>
</components>

=== fazarei/VlineDriverVersion2/com/netdimen/custom/lds/conf/componentsExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
*************************************************************
This file is used to define various types of EKP components,
including transactions and reports.

$Revision: 1.9 $
*************************************************************
-->
<components xmlns="http://www.netdimensions.com/xml/ns/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.netdimensions.com/xml/ns/components components.xsd">

	<transactions>
		<transaction>
			<tx-code>LDSHOME</tx-code>
			<tx-type>HOMEPAGE</tx-type>
			<feature>MyHome</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsHome</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LEARNINGSPACE</tx-code>
			<feature>KnowledgeCenter</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsLearningSpace</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>CATFRAMES</tx-code>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsCatFrames</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LDSCAT_TOP</tx-code>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsCatTop</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSCATINTRO</tx-code>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsCatIntro</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSCAT_LEFT</tx-code>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsCatLeft</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSSEARCHRESULT</tx-code>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsSearchResult</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSSEARCHRESULT2</tx-code>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsSearchResult2</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSSEARCHCAT</tx-code>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsSearchCAT</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSTopMenu</tx-code>
			<tx-type>MENU</tx-type>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LDSTopMenu</class>
			<requires-authentication>false</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSCESSELFREGISTER</tx-code>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsCesSelfRegister</class>
			<requires-authentication>false</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LDSCESSAVESELFREG</tx-code>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsCesSaveSelfRegister</class>
			<requires-authentication>false</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LDSFCHSSO</tx-code>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.tx.auth.HttpSso</class>
			<requires-authentication>false</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>MIGRATEUSERPROMPT</tx-code>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.MigrateUserPrompt</class>
			<requires-authentication>false</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>LDSHOMEMODULEANDNEWS</tx-code>
			<tx-type>HOMEPAGE</tx-type>
			<feature>MyHome</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.LdsHomeModuleAndNews</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSSTANDARDTOPTABS</tx-code>
			<tx-type>MENU</tx-type>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.tx.screen.StandardTopTabs</class>
			<requires-authentication>false</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
		<transaction>
			<tx-code>LDSFOOTER</tx-code>
			<tx-type>MENU</tx-type>
			<feature>System</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.custom.lds.tx.screen.LdsFooter</class>
			<requires-authentication>true</requires-authentication>
		</transaction>
		<transaction>
			<tx-code>FORMAT1</tx-code>
			<tx-type>CATALOGFORMAT</tx-type>
			<feature>Catalog</feature>
			<access-level>ReadAccess</access-level>
			<class>com.netdimen.tx.catalogviewer.Format1</class>
			<requires-authentication>true</requires-authentication>
			<nonblocking-transaction>true</nonblocking-transaction>
		</transaction>
	</transactions>
</components>
